// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Models;

namespace StudentAPI.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20210707211514_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentAPI.Models.StudentDetail", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentCollege")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentCourse")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StudentDetailStudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentDetailStudentId");

                    b.ToTable("StudentDetails");
                });

            modelBuilder.Entity("StudentAPI.Models.StudentIndex", b =>
                {
                    b.Property<int>("IndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentDateMark")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentMark")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("StudentSubject")
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("IndexId");

                    b.ToTable("StudentIndexs");
                });

            modelBuilder.Entity("StudentAPI.Models.StudentDetail", b =>
                {
                    b.HasOne("StudentAPI.Models.StudentDetail", null)
                        .WithMany("StudentIndexID")
                        .HasForeignKey("StudentDetailStudentId");
                });

            modelBuilder.Entity("StudentAPI.Models.StudentDetail", b =>
                {
                    b.Navigation("StudentIndexID");
                });
#pragma warning restore 612, 618
        }
    }
}
